### ISSUE TITLE
Remove reference to Koa11y (no update in 5 years)

### ISSUE THREAD

**Issue by millette** [pa11y/pa11y.github.io#102]
Might be a good idea to remove Koa11y from

* https://github.com/pa11y/pa11y.github.io/blob/master/pages/home.md#other-ways-to-use-pa11y
* https://github.com/pa11y/pa11y/blob/master/README.md#pa11y

Or at least add a note indicating it hasn't been updated in 5 years.

**Comment by josebolos** [comment]
Good catch @millette! Shame about Koa11y. I've removed the mentions in both repos.

Thanks for creating the issue!
