### ISSUE TITLE
Missing entries on Tutorial page

### ISSUE THREAD

**Issue by StopinskiThomas** [pa11y/pa11y.github.io#119]
On the page https://github.com/pa11y/pa11y.github.io/blob/main/pages/tutorials.md the are the entries missing.
All that I csn see is 

{% include tutorial-list.html tutorials=site.data.tutorials.dashboard %}

**Comment by josebolos** [comment]
Hi @StopinskiThomas!

That's a template file, the content you're looking for is available on the Pa11y site:
https://pa11y.org/tutorials/
