### ISSUE TITLE
Writing guide: decide on a heading case style

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y.github.io#39]
We use two different heading cases across the site - title case and sentence case. We really need to standardise this otherwise the text will look untidy (we had the same problem with http://cruft.io/). It's most noticeable on pages like this: http://pa11y.github.io/contributing/developers/ where title case is used for h1 and h2 headings, and sentence case is used for h3. Whatever we choose, it needs to be consistent. 

I'm in favour of sentence case, because that's what [Nature](http://www.nature.com) uses ;) (but also because its internal logic is [much simpler](http://www.grammarcheck.net/capitalization-in-titles-101/))

- More than you've probably ever wanted to read on heading cases: https://en.wikipedia.org/wiki/Letter_case#Headings_and_publication_titles
- In support of sentence case: http://www.stickycontent.com/blog/are-you-team-title-case-or-team-sentence-case
- In support of title case (sorry): http://www.komarketingassociates.com/blog/a-case-for-title-case/

**Comment by rowanmanning** [comment]
I'm up for sentence case, after reading those articles 👍

**Comment by rowanmanning** [comment]
Closing this. I've opened #40 to do the actual work 👍
