### ISSUE TITLE
Reconsider the "Suggest an edit to this page" link

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y.github.io#45]
Currently the "Suggest an edit to this page" link is tucked away in the footer. I'm not sure whether this is the ideal place for it, and not even sure if anyone would think to _look_ for this link.

I'm not sure where else it'd be better. One idea I had is if maybe it's sticky and just a pencil icon? We could pop it somewhere in the top corner or something.

**Comment by josebolos** [comment]
Thanks! I think the current link is pretty explicit and, considering our lack of resources, it's unlikely we're going to make design changes to the site any time soon.
