### ISSUE TITLE
Design the website

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y.github.io#57]
Currently this site has not been considered from a design perspective. It shows that Pa11y is mostly contributed to mostly by engineers and it'd be nice to have something that looks a bit better.

Visual style is pretty open-ended, as our [brand and design guidelines](https://pa11y.org/contributing/designers/) aren't in place. Designing the website could be a way for someone to help set the direction of [the dashboard](https://github.com/pa11y/pa11y-dashboard), [Sidekick](https://github.com/pa11y/sidekick), and other future projects.

It's a pretty blank canvas, and we'd be happy for this to either be provided as design assets or for someone to implement it in code at the same time.

If you're a designer and not comfortable using GitHub, then it's fine to contact me in a different way and I'll post transcripts and your work here.

## Previous iterations

We've had designs _started_ in the past, but for various reasons the people working on these weren't able to continue. I wanted to document them here as possible inspiration and to make sure that we have all of them captured on GitHub.

### March 2017

A couple of home page designs by Luke Stavenhagen. _Note, the stock images are placeholders and have not been purchased._

<table>
<tr>
<td width="50%"><img src="https://user-images.githubusercontent.com/138944/61724872-afd8c800-ad66-11e9-8540-2ae2863ade83.png" alt="Pa11y Home Page 1"/></td>
<td width="50%"><img src="https://user-images.githubusercontent.com/138944/61724875-b23b2200-ad66-11e9-8052-b9fff9eb1566.png" alt="Pa11y Home Page 2"/></td>
</tr>
</table>

### May 2018

A home page design by Perry Harlock.

<table>
<tr>
<td width="50%"><img src="https://user-images.githubusercontent.com/138944/61725118-15c54f80-ad67-11e9-924a-6faddffb0240.jpg" alt="Pa11y Home Page 1"/></td>
<td width="50%">&nbsp;</td>
</tr>
</table>

**Comment by arndissler** [comment]
Is this issue still valid? If not, can we close it?

**Comment by Erioldoesdesign** [comment]
Hey there 👋  it seems like one of the first things to do is to come up with the aims of the website from a user perspective as well as the teams objectives: What do you want to encourage? Who do you serve etc.

If you're happy with someone being a slow burn on contributing then I'm happy to, I wonder if you'd like more regularity/consistency though?

**Comment by josebolos** [comment]
Hi @Erioldoesdesign!

Thanks so much for your offer! If I recall correctly there was a bit of work done around this last year that wasn't documented here for some reason. Let me try to find out what's the status of that, and we'll get back to you.

**Comment by josebolos** [comment]
It's unlikely we're going to redesign right now, so I'm closing the issue for now. We may revisit at a later date if things change.
