### ISSUE TITLE
Add Koa11y Desktop App to site

### ISSUE THREAD

**Issue by TheJaredWilcurt** [pa11y/pa11y.github.io#62]
I've been working on a desktop app that gives a UI to the Pa11y command line application. I just finished it up and published it today.

Release notes:

* https://github.com/TheJaredWilcurt/Koa11y/releases

Download page:

* http://thejaredwilcurt.github.io/Koa11y

It will allow people to use Pa11y in just a few seconds (download, unzip, double-click), as it removes all the technical hurdles involved in running it. Everything required to run it is in one self-contained portable app. 

On top of the functionality that comes out of the box with Pa11y, I've added some extra features involving image stats and the type of reports it can generate (markdown, html, csv, json, xml).

It's completely open source.

**Comment by rowanmanning** [comment]
@TheJaredWilcurt this is awesome! Genuinely so cool, and we'll be more than happy to link from the website :) we're just discussing adding a new section for "other ways to use Pa11y" or something.

I think you've made my week by releasing this, I'll tweet from @pa11yorg later if you're happy for me to do that too.

**Comment by hollsk** [comment]
I love this so much. I'll add a new section to the Pa11y site for it today, it would help so many people! <3

**Comment by TheJaredWilcurt** [comment]
Awesome, feel free to share it with whomever.
