### ISSUE TITLE
Update DNS record to enable SSL encryption

### ISSUE THREAD

**Issue by arndissler** [pa11y/pa11y.github.io#86]
Hello over there,

unfortunately it's not possible to use the pa11y website with SSL encryption, in Chrome and other browsers such as Firefox and Safari, the site is marked as "unsecure" or is unreachable, when the users typing "https://pa11y.org" directly into the location bar. This is caused by misconfigured within the DNS and should be changed.

DNS records for apex domain pa11y.org as of 2018-12-14:
```
pa11y.org.		10799	IN	A	192.30.252.153
pa11y.org.		10799	IN	A	192.30.252.154
pa11y.org.		10799	IN	NS	ns-126-a.gandi.net.
pa11y.org.		10799	IN	NS	ns-58-b.gandi.net.
pa11y.org.		10799	IN	NS	ns-62-c.gandi.net.
pa11y.org.		10799	IN	SOA	ns1.gandi.net. hostmaster.gandi.net. 1544659200 10800 3600 604800 10800
```

According to [setting up an APEX domain](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider) the `A record`s must be the same as for `pa11y.github.io`:

```
pa11y.org.	3599	IN	A	185.199.111.153
pa11y.org.	3599	IN	A	185.199.108.153
pa11y.org.	3599	IN	A	185.199.109.153
pa11y.org.	3599	IN	A	185.199.110.153
```
The `NS` and `SOA` records remain unchanged.

Afterwards it should be possible to use the pa11y website with a valid SSL certificate and one should [enforce SSL encryption](https://help.github.com/articles/securing-your-github-pages-site-with-https/#enforcing-https-for-your-github-pages-site) for the project website.

**Comment by rowanmanning** [comment]
Thanks @arndissler for opening, we've _finally_ got around to enabling HTTPS on https://pa11y.org/
